name: NodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.7]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        node fullbuild.js

    - name: "GitHub Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      continue-on-error: true
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "fullbuild-${{github.run_number}}"
        prerelease: true
        title: "fullbuild ${{github.run_number}}"
        files: |
          OpenAttachmentByExtension.xpi
